### 1.  What are the most common NumPy data types?
#### As the name suggest(Numerical Python), Numers are the most common data types in Numpy array.

### 2. How to change the data type of a NumPy array?
#### There many ways to convert data type of Numpy array,
1. Using astype()

In [6]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(a, a.dtype)

[1 2 3 4 5 6] int32


In [7]:
# change data type to float using astype()
b=a.astype(float)
print(b, b.dtype)

[1. 2. 3. 4. 5. 6.] float64


2. Using parameter dtype='f' or 'float'

In [8]:
c=np.array(a, dtype='f')
c

array([1., 2., 3., 4., 5., 6.], dtype=float32)

### 3. What are the advantages of numpy array over a regular python list?
#### Advatages of array over list are,
1. Consumes less memory.
2. Fast as compared to the python List.
3. Convenient to use.

### 4.  What is the easiest way to calculate percentiles when using Python?
#### Using numpy function `percentile` we can calculate percentile of any quantile value.

In [14]:
arr=[1,2,5,1,6,2,7,3,8,5,8,2,0,7,6]
np.percentile(arr, q=[0.25, 0.5, 0.75, 0.9, 0.95, 0.99])

array([0.035 , 0.07  , 0.105 , 0.126 , 0.133 , 0.1386])

### 5. What are the different ways of creating DataFrame in pandas?
#### We can create data frame from list, tuple, dictionary data structures. `pandas.DataFrame` is used to create dataframe in python.

In [15]:
#dataframe using list
pd.DataFrame({'name':['suraj','siya','riya','jiya','ravi'], 'age':[27, 28, 25, 24, 30]})

name  age
0  suraj   27
1   siya   28
2   riya   25
3   jiya   24
4   ravi   30

In [20]:
#dataframe using tuple
pd.DataFrame({'name':('suraj','siya','riya','jiya','ravi'), 'age':(27, 28, 25, 24, 30)})

name  age
0  suraj   27
1   siya   28
2   riya   25
3   jiya   24
4   ravi   30

### 6.  What do you mean by data aggregation?
#### Data aggregation is the process where data is gathered and expressed in a summary form. Summary can mean, median, percentage, variance, standard deviation etc.

In [34]:
df=pd.DataFrame({'name':('suraj','siya','riya','jiya','ravi'), 'age':(27, 28, 25, 24, 30), 'salary':(2000,5000,4000,3000,6000)})
df[['age','salary']].aggregate([np.sum, np.mean, np.median, np.std, np.var])

age        salary
sum     134.000000  2.000000e+04
mean     26.800000  4.000000e+03
median   27.000000  4.000000e+03
std       2.387467  1.581139e+03
var       5.700000  2.500000e+06

### 7. What do you mean by pandas indexing?
####  Indexing in pandas means simply selecting particular rows and columns of data from a DataFrame.

In [37]:
df['age'][0:4]

0    27
1    28
2    25
3    24
Name: age, dtype: int64

### 8. What is the best way to generate histograms in matplotlib?
#### Using `matplotlib.pyplot.histplot` we can create histogram.

### 9. Can you provide me with an example of when a scatter graph would be more appropriate than a line chart?
#### Scatter plot is used to plot the relationship between two continoues numerical columns where the Line chart is used when we want to see the trend of some data wrt time.

### 10. Explain the plots you will use for analyzing one categorical, one numerical, two categorical, two numerical, one categorical and one numerical columns?
1. Univariate analysis for one categorical column, it is more appropriate to use `countplot`.
2. Univariate analysis for one numerical columns, it is more appropriate to use `boxplot, histogram, kde plot, distplot`.
3. Bivariate analysis for 2 categorical column, it is better to use `crosstab`.
4. Bivariate analysis for 2 numerical column, it is appropriate to use `scatterplot`.
5. Bivariate for one numerical and other categorical, we use `barplot` sometimes `boxplots`.
6. To see the relationship between all numerical features we use correlation matrix ploted using `heatmap`.